### ISSUE TITLE
[Request] Toggle core mode based on requirements

### ISSUE THREAD

**Issue by Pandorafoxxx** [rhelmot/CelesteRandomizer#187]
this would just allow there to be different combinations, harder rooms in different core modes while not needing to remove easier ones. for example: 8a c-01 it is possible to go to the right with one dash in the hot mode, but at the same time it is possible dashless in the cold mode. im not sure how possible this would be to implement but it has been something on my mind a while so i might aswell put it here.

an example config of what i mean incase it isnt clear.
```
ReqOut:
  Or:
  - Dashes: one
    Core: hot
  - Dashes: zero
    Core: cold

**Comment by rhelmot** [comment]
I think a more interesting version of this is that you should be able to specify the same room multiple times, which honestly I think might already be supported. Try this?

```
- Room: "a-00"
  Core:
    All: hot
  Holes:
    - Side: Left
      Idx: 0
      Kind: inout
- Room: "a-00"
  Core:
    All: cold
  Holes:
    - Side: Left
      Idx: 1
      Kind: inout
```
