### ISSUE TITLE
Room a-03 with bubbles and breakable blocks from 4a shows up backwards in dashless, not possible.

### ISSUE THREAD

**Issue by masrock9** [rhelmot/CelesteRandomizer#28]

**Comment by rhelmot** [comment]
Here's the config for that room:

```
  - Room: "a-03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "Berry"
      ReqBoth:
        Dashes: zero
    - To: "Right"
      ReqOut:
        Dashes: zero
      ReqIn:
        Dashes: one
    Subrooms:
    - Room: "Right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "Berry"
        ReqBoth:
          Dashes: zero
    - Room: "Berry"
      Collectables:
      - Idx: 0
```

From what I can tell, it shouldn't make you try to traverse right to left without any dashes... can you provide a seed that does this?
