### ISSUE TITLE
issue with 8A room c-03b

### ISSUE THREAD

**Issue by 3ddyy** [rhelmot/CelesteRandomizer#31]
```yaml
  - Room: "c-03b"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Down
      Idx: 2
      Kind: inout
```
i encounter this room (as 2nd room, go up+right from the start) using:
Seed: 003244
all maps enabled
no repeat rooms
no strange holes
pathway
short
0 dashes
normal difficulty

I enter from the bottom and i can't get out. i believe the 
```yaml
    - Side: Down
      Idx: 0
      Kind: in
```
should be
```yaml
    - Side: Down
      Idx: 0
      Kind: out
```
(change in to out)
