### ISSUE TITLE
Delete spawn points for non-paths

### ISSUE THREAD

**Issue by iolight** [rhelmot/CelesteRandomizer#8]
Trying to go down a non-path may trigger a spawn point and prevent any backtracking.

**Comment by rhelmot** [comment]
This is doable now! It is an ongoing project but the syntax is available.

The testcase we were looking into before:

![image](https://user-images.githubusercontent.com/2498805/82765771-64e87080-9dce-11ea-82f6-4a6215f0e1de.png)

Is resolved with the following code under the relevant Room entry:

```
    Tweaks:
    - ID: 4     # change respawn trigger in top right
      Update:
        Remove: true
```

As an aside, you can also add new spawn points to levels to make it so that resetting doesn't perform a backtrack for you. For example, the following spawn is added by the following syntax:

```
    Tweaks:
    - Name: spawn
      Update:
        Add: true
        X: 240
        Y: 208
```

![image](https://user-images.githubusercontent.com/2498805/82765717-ed1a4600-9dcd-11ea-9f49-dced2824ceed.png)

You can combine the two syntax and specify neither Add nor Remove to update attributes (currently just X Y Width Height) for existing entities.
